import type {
  ChapterOfficer,
  ChapterData,
  MemberData,
  EventData,
  ArticleData,
  DocumentData,
  MerchandiseData,
  SponsorData,
  EmergencyContactData,
} from '@/types';

export type {
  ChapterOfficer,
  ChapterData,
  MemberData,
  EventData,
  ArticleData,
  DocumentData,
  MerchandiseData,
  SponsorData,
  EmergencyContactData,
};
export { CENTRAL_OFFICERS } from '@/types';

export const INITIAL_CHAPTERS: ChapterData[] = [
  {
    id: 'ch-1',
    name: 'NTCI Chapter Jakarta Raya',
    slug: 'jakarta-raya',
    region: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    leaderName: 'Bambang "Turbo" Wijaya',
    viceLeaderName: 'Bro Herman "Nmax"',
    secretaryName: 'Bro Rizky Maulana',
    treasurerName: 'Sis Maya Kartika',
    touringOfficerName: 'Bro Fikri Syahputra',
    humasOfficerName: 'Bro Anton Wijaya',
    contactPhone: '+62 812-3456-7890',
    kopdarLocation: 'Pintu 1 Senayan / Plaza Mandiri, Jakarta Pusat',
    kopdarSchedule: 'Setiap Rabu Malam (20:00 WIB)',
    status: 'DECLARED',
    memberCount: 8,
    officers: [
      {
        role: 'Ketua Chapter',
        name: 'Bambang "Turbo" Wijaya',
        nra: 'NTCI-JKT-001',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        phone: '+62 812-3456-7890',
      },
      {
        role: 'Wakil Ketua Chapter',
        name: 'Bro Herman "Nmax"',
        nra: 'NTCI-JKT-008',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        phone: '+62 812-1111-2222',
      },
      {
        role: 'Sekretaris Chapter',
        name: 'Bro Rizky Maulana',
        nra: 'NTCI-JKT-012',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 812-3333-4444',
      },
      {
        role: 'Bendahara Chapter',
        name: 'Sis Maya Kartika',
        nra: 'NTCI-JKT-015',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
        phone: '+62 812-5555-6666',
      },
      {
        role: 'Divisi Touring & Road Captain',
        name: 'Bro Fikri Syahputra',
        nra: 'NTCI-JKT-020',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 812-7777-8888',
      },
      {
        role: 'Divisi Humas & Publikasi',
        name: 'Bro Anton Wijaya',
        nra: 'NTCI-JKT-025',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
        phone: '+62 812-9999-0000',
      },
    ],
  },
  {
    id: 'ch-2',
    name: 'NTCI Chapter Bandung Juara',
    slug: 'bandung-juara',
    region: 'Jawa Barat',
    city: 'Bandung',
    leaderName: 'Dicky "Speed" Hendrawan',
    viceLeaderName: 'Kang Asep Ridwan',
    secretaryName: 'Kang Yudi Pratama',
    treasurerName: 'Teh Lina Marlina',
    touringOfficerName: 'Kang Agum Ginanjar',
    humasOfficerName: 'Kang Farhan Permana',
    contactPhone: '+62 813-9876-5432',
    kopdarLocation: 'Gedung Sate / Jl. Diponegoro No. 22',
    kopdarSchedule: 'Jumat Malam Minggu Ke-1 & Ke-3 (20:30 WIB)',
    status: 'DECLARED',
    memberCount: 7,
    officers: [
      {
        role: 'Ketua Chapter',
        name: 'Dicky "Speed" Hendrawan',
        nra: 'NTCI-BDG-002',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        phone: '+62 813-9876-5432',
      },
      {
        role: 'Wakil Ketua Chapter',
        name: 'Kang Asep Ridwan',
        nra: 'NTCI-BDG-004',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 813-1111-2222',
      },
      {
        role: 'Sekretaris Chapter',
        name: 'Kang Yudi Pratama',
        nra: 'NTCI-BDG-007',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 813-3333-4444',
      },
      {
        role: 'Bendahara Chapter',
        name: 'Teh Lina Marlina',
        nra: 'NTCI-BDG-010',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
        phone: '+62 813-5555-6666',
      },
      {
        role: 'Divisi Touring & Road Captain',
        name: 'Kang Agum Ginanjar',
        nra: 'NTCI-BDG-012',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
        phone: '+62 813-7777-8888',
      },
      {
        role: 'Divisi Humas',
        name: 'Kang Farhan Permana',
        nra: 'NTCI-BDG-015',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        phone: '+62 813-9999-0000',
      },
    ],
  },
  {
    id: 'ch-3',
    name: 'NTCI Chapter Surabaya Coastal',
    slug: 'surabaya-coastal',
    region: 'Jawa Timur',
    city: 'Surabaya',
    leaderName: 'Rendy Pratama',
    viceLeaderName: 'Cak Sugeng Raharjo',
    secretaryName: 'Cak Bayu Setiawan',
    treasurerName: 'Ning Anita Wati',
    touringOfficerName: 'Cak Doni Kurniawan',
    humasOfficerName: 'Cak Eko Prasetyo',
    contactPhone: '+62 856-7891-2345',
    kopdarLocation: 'Taman Bungkul & Suramadu Rest Area',
    kopdarSchedule: 'Sabtu Malam (19:30 WIB)',
    status: 'DECLARED',
    memberCount: 6,
    officers: [
      {
        role: 'Ketua Chapter',
        name: 'Rendy Pratama',
        nra: 'NTCI-SUB-003',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
        phone: '+62 856-7891-2345',
      },
      {
        role: 'Wakil Ketua Chapter',
        name: 'Cak Sugeng Raharjo',
        nra: 'NTCI-SUB-005',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        phone: '+62 856-1111-2222',
      },
      {
        role: 'Sekretaris Chapter',
        name: 'Cak Bayu Setiawan',
        nra: 'NTCI-SUB-009',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 856-3333-4444',
      },
      {
        role: 'Bendahara Chapter',
        name: 'Ning Anita Wati',
        nra: 'NTCI-SUB-011',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
        phone: '+62 856-5555-6666',
      },
      {
        role: 'Divisi Touring',
        name: 'Cak Doni Kurniawan',
        nra: 'NTCI-SUB-014',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 856-7777-8888',
      },
      {
        role: 'Divisi Humas',
        name: 'Cak Eko Prasetyo',
        nra: 'NTCI-SUB-018',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        phone: '+62 856-9999-0000',
      },
    ],
  },
  {
    id: 'ch-4',
    name: 'NTCI Chapter Yogyakarta Mataram',
    slug: 'yogyakarta-mataram',
    region: 'DI Yogyakarta',
    city: 'Yogyakarta',
    leaderName: 'Agus Setiawan',
    viceLeaderName: 'Mas Bambang Sutrisno',
    secretaryName: 'Mas Danang Wijaya',
    treasurerName: 'Mbak Dewi Lestari',
    touringOfficerName: 'Mas Gito Raharjo',
    humasOfficerName: 'Mas Dimas Anggoro',
    contactPhone: '+62 818-0123-4567',
    kopdarLocation: 'Alun-Alun Utara / Titik Nol Km Jogja',
    kopdarSchedule: 'Sabtu Malam Minggu Ke-2 & Ke-4 (20:00 WIB)',
    status: 'DECLARED',
    memberCount: 6,
    officers: [
      {
        role: 'Ketua Chapter',
        name: 'Agus Setiawan',
        nra: 'NTCI-JOG-005',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 818-0123-4567',
      },
      {
        role: 'Wakil Ketua Chapter',
        name: 'Mas Bambang Sutrisno',
        nra: 'NTCI-JOG-007',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        phone: '+62 818-1111-2222',
      },
      {
        role: 'Sekretaris Chapter',
        name: 'Mas Danang Wijaya',
        nra: 'NTCI-JOG-010',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 818-3333-4444',
      },
      {
        role: 'Bendahara Chapter',
        name: 'Mbak Dewi Lestari',
        nra: 'NTCI-JOG-012',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
        phone: '+62 818-5555-6666',
      },
      {
        role: 'Divisi Touring',
        name: 'Mas Gito Raharjo',
        nra: 'NTCI-JOG-015',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
        phone: '+62 818-7777-8888',
      },
      {
        role: 'Divisi Humas',
        name: 'Mas Dimas Anggoro',
        nra: 'NTCI-JOG-018',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        phone: '+62 818-9999-0000',
      },
    ],
  },
  {
    id: 'ch-5',
    name: 'NTCI Chapter Bali Paradise',
    slug: 'bali-paradise',
    region: 'Bali',
    city: 'Denpasar',
    leaderName: 'I Made Suardana',
    viceLeaderName: 'I Wayan Gede',
    secretaryName: 'Ni Putu Ayu',
    treasurerName: 'I Nyoman Kadek',
    touringOfficerName: 'I Ketut Rai',
    humasOfficerName: 'I Made Agus',
    contactPhone: '+62 878-6543-2109',
    kopdarLocation: 'Pantai Matahari Terbit Sanur',
    kopdarSchedule: 'Minggu Sore (16:30 WITA)',
    status: 'DECLARED',
    memberCount: 6,
    officers: [
      {
        role: 'Ketua Chapter',
        name: 'I Made Suardana',
        nra: 'NTCI-BAL-006',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 878-6543-2109',
      },
      {
        role: 'Wakil Ketua Chapter',
        name: 'I Wayan Gede',
        nra: 'NTCI-BAL-008',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        phone: '+62 878-1111-2222',
      },
      {
        role: 'Sekretaris Chapter',
        name: 'Ni Putu Ayu',
        nra: 'NTCI-BAL-011',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
        phone: '+62 878-3333-4444',
      },
      {
        role: 'Bendahara Chapter',
        name: 'I Nyoman Kadek',
        nra: 'NTCI-BAL-014',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 878-5555-6666',
      },
      {
        role: 'Divisi Touring',
        name: 'I Ketut Rai',
        nra: 'NTCI-BAL-017',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
        phone: '+62 878-7777-8888',
      },
      {
        role: 'Divisi Humas',
        name: 'I Made Agus',
        nra: 'NTCI-BAL-020',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        phone: '+62 878-9999-0000',
      },
    ],
  },
  {
    id: 'ch-6',
    name: 'NTCI Chapter Medan Sumatra',
    slug: 'medan-sumatra',
    region: 'Sumatera Utara',
    city: 'Medan',
    leaderName: 'Fahmi Siregar',
    viceLeaderName: 'Bang Ucok Harahap',
    secretaryName: 'Bang Budi Nasution',
    treasurerName: 'Kak Sarah Hasibuan',
    touringOfficerName: 'Bang Taufik Hidayat',
    humasOfficerName: 'Bang Reza Pahlevi',
    contactPhone: '+62 821-4321-8765',
    kopdarLocation: 'Lapangan Merdeka Medan / Lapangan Benteng',
    kopdarSchedule: 'Jumat Malam (20:00 WIB)',
    status: 'DECLARED',
    memberCount: 6,
    officers: [
      {
        role: 'Ketua Chapter',
        name: 'Fahmi Siregar',
        nra: 'NTCI-MED-007',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        phone: '+62 821-4321-8765',
      },
      {
        role: 'Wakil Ketua Chapter',
        name: 'Bang Ucok Harahap',
        nra: 'NTCI-MED-009',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        phone: '+62 821-1111-2222',
      },
      {
        role: 'Sekretaris Chapter',
        name: 'Bang Budi Nasution',
        nra: 'NTCI-MED-012',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 821-3333-4444',
      },
      {
        role: 'Bendahara Chapter',
        name: 'Kak Sarah Hasibuan',
        nra: 'NTCI-MED-015',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
        phone: '+62 821-5555-6666',
      },
      {
        role: 'Divisi Touring',
        name: 'Bang Taufik Hidayat',
        nra: 'NTCI-MED-018',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 821-7777-8888',
      },
      {
        role: 'Divisi Humas',
        name: 'Bang Reza Pahlevi',
        nra: 'NTCI-MED-022',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
        phone: '+62 821-9999-0000',
      },
    ],
  },
  {
    id: 'ch-7',
    name: 'NTCI Chapter Semarang Central (Prospek)',
    slug: 'semarang-central',
    region: 'Jawa Tengah',
    city: 'Semarang',
    leaderName: 'Bro Hendra "Turbo" Gunawan',
    viceLeaderName: 'Bro Arif Hidayat',
    contactPhone: '+62 813-2222-3333',
    kopdarLocation: 'Simpang Lima Semarang / Tugu Muda',
    kopdarSchedule: 'Sabtu Malam Minggu Ke-2 (20:00 WIB)',
    status: 'EMBRYO',
    memberCount: 2,
    officers: [
      {
        role: 'Ketua Chapter (Prospek)',
        name: 'Bro Hendra "Turbo" Gunawan',
        nra: 'NTCI-SMG-001',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        phone: '+62 813-2222-3333',
      },
      {
        role: 'Wakil Ketua Chapter',
        name: 'Bro Arif Hidayat',
        nra: 'NTCI-SMG-003',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 813-4444-5555',
      },
    ],
  },
  {
    id: 'ch-8',
    name: 'NTCI Chapter Makassar Celebes (Prospek)',
    slug: 'makassar-celebes',
    region: 'Sulawesi Selatan',
    city: 'Makassar',
    leaderName: 'Daeng Rahmat',
    viceLeaderName: 'Daeng Syamsul',
    contactPhone: '+62 852-9988-7766',
    kopdarLocation: 'Pantai Losari Makassar',
    kopdarSchedule: 'Jumat Malam (20:30 WITA)',
    status: 'EMBRYO',
    memberCount: 2,
    officers: [
      {
        role: 'Ketua Chapter (Prospek)',
        name: 'Daeng Rahmat',
        nra: 'NTCI-MKS-001',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
        phone: '+62 852-9988-7766',
      },
      {
        role: 'Wakil Ketua Chapter',
        name: 'Daeng Syamsul',
        nra: 'NTCI-MKS-002',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
        phone: '+62 852-1111-3333',
      },
    ],
  },
];

export const INITIAL_MEMBERS: MemberData[] = [
  // Chapter Jakarta Raya Members (All 8 Officers & Members)
  {
    id: 'mem-1',
    fullName: 'Bambang "Turbo" Wijaya',
    nra: 'NTCI-JKT-001',
    email: 'admin@ntci.or.id',
    phone: '+62 812-3456-7890',
    role: 'SUPER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Jakarta Raya',
    chapterSlug: 'jakarta-raya',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'B 1904 NTCI',
    motorColor: 'Magma Black Metallic',
    motorMods: 'Akrapovic Exhaust, Carbon Body Trim, Y-CVT Sport Remap',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    joinedDate: '10 Januari 2024',
  },
  {
    id: 'mem-1b',
    fullName: 'Bro Herman "Nmax"',
    nra: 'NTCI-JKT-008',
    email: 'herman.jkt@ntci.or.id',
    phone: '+62 812-1111-2222',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Jakarta Raya',
    chapterSlug: 'jakarta-raya',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'B 8888 NMX',
    motorColor: 'Elixir Dark Red',
    motorMods: 'Windshield Tall Touring, Rear Box Givi 43L',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    joinedDate: '12 Januari 2024',
  },
  {
    id: 'mem-1c',
    fullName: 'Bro Rizky Maulana',
    nra: 'NTCI-JKT-012',
    email: 'rizky.jkt@ntci.or.id',
    phone: '+62 812-3333-4444',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Jakarta Raya',
    chapterSlug: 'jakarta-raya',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'B 1212 RZK',
    motorColor: 'Magma Black',
    motorMods: 'Ohlins Suspension, LED Foglights',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '18 Januari 2024',
  },
  {
    id: 'mem-1d',
    fullName: 'Sis Maya Kartika',
    nra: 'NTCI-JKT-015',
    email: 'maya.jkt@ntci.or.id',
    phone: '+62 812-5555-6666',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Jakarta Raya',
    chapterSlug: 'jakarta-raya',
    motorModel: 'Nmax Turbo Neo Version',
    motorYear: '2024',
    motorPlate: 'B 1515 MYA',
    motorColor: 'Dull Blue Metallic',
    motorMods: 'Crashbar Full Set, Phone Holder Wireless',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    joinedDate: '22 Januari 2024',
  },
  {
    id: 'mem-1e',
    fullName: 'Bro Fikri Syahputra',
    nra: 'NTCI-JKT-020',
    email: 'fikri.jkt@ntci.or.id',
    phone: '+62 812-7777-8888',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Jakarta Raya',
    chapterSlug: 'jakarta-raya',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'B 2020 RC',
    motorColor: 'Magma Black',
    motorMods: 'RCS19 Master Cylinder, Dual Disc Brakes Custom',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '01 Februari 2024',
  },
  {
    id: 'mem-1f',
    fullName: 'Bro Anton Wijaya',
    nra: 'NTCI-JKT-025',
    email: 'anton.jkt@ntci.or.id',
    phone: '+62 812-9999-0000',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Jakarta Raya',
    chapterSlug: 'jakarta-raya',
    motorModel: 'Nmax Turbo Standard',
    motorYear: '2024',
    motorPlate: 'B 2525 ANT',
    motorColor: 'Ceramic Grey',
    motorMods: 'Velg Repaint Gold, Exhaust R9 Racing',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    joinedDate: '05 Februari 2024',
  },
  {
    id: 'mem-4',
    fullName: 'Siti Nurhaliza',
    nra: 'NTCI-JKT-014',
    email: 'siti.ladybiker@ntci.or.id',
    phone: '+62 812-9988-7766',
    role: 'MEMBER',
    isVerified: true,
    chapterName: 'NTCI Chapter Jakarta Raya',
    chapterSlug: 'jakarta-raya',
    motorModel: 'Nmax Turbo Neo Version',
    motorYear: '2024',
    motorPlate: 'B 4321 LADY',
    motorColor: 'Dull Blue Metallic',
    motorMods: 'Top Box Shad 45L, LED Foglights Dual Color',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    joinedDate: '12 April 2024',
  },
  {
    id: 'mem-1g',
    fullName: 'Bro Doni Setiawan',
    nra: 'NTCI-JKT-032',
    email: 'doni.jkt@ntci.or.id',
    phone: '+62 812-4444-9999',
    role: 'MEMBER',
    isVerified: true,
    chapterName: 'NTCI Chapter Jakarta Raya',
    chapterSlug: 'jakarta-raya',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'B 3232 DNI',
    motorColor: 'Magma Black',
    motorMods: 'Intercom Cardo Packtalk, Touring Windshield',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    joinedDate: '15 Mei 2024',
  },

  // Chapter Bandung Juara Members
  {
    id: 'mem-2',
    fullName: 'Dicky "Speed" Hendrawan',
    nra: 'NTCI-BDG-002',
    email: 'dicky@ntci.or.id',
    phone: '+62 813-9876-5432',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bandung Juara',
    chapterSlug: 'bandung-juara',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'D 3333 NMX',
    motorColor: 'Elixir Dark Red',
    motorMods: 'Ohlins Rear Suspension, Brembo Master Cylinder',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    joinedDate: '15 Februari 2024',
  },
  {
    id: 'mem-2b',
    fullName: 'Kang Asep Ridwan',
    nra: 'NTCI-BDG-004',
    email: 'asep.bdg@ntci.or.id',
    phone: '+62 813-1111-2222',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bandung Juara',
    chapterSlug: 'bandung-juara',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'D 4444 ASP',
    motorColor: 'Magma Black',
    motorMods: 'Crashbar Tourer, Foglights Cree 60W',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '20 Februari 2024',
  },
  {
    id: 'mem-2c',
    fullName: 'Kang Yudi Pratama',
    nra: 'NTCI-BDG-007',
    email: 'yudi.bdg@ntci.or.id',
    phone: '+62 813-3333-4444',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bandung Juara',
    chapterSlug: 'bandung-juara',
    motorModel: 'Nmax Turbo Standard',
    motorYear: '2024',
    motorPlate: 'D 7777 YDI',
    motorColor: 'Ceramic Grey',
    motorMods: 'Velg Bronze Metallic, Carbon Tail Light',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '28 Februari 2024',
  },
  {
    id: 'mem-2d',
    fullName: 'Teh Lina Marlina',
    nra: 'NTCI-BDG-010',
    email: 'lina.bdg@ntci.or.id',
    phone: '+62 813-5555-6666',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bandung Juara',
    chapterSlug: 'bandung-juara',
    motorModel: 'Nmax Turbo Neo Version',
    motorYear: '2024',
    motorPlate: 'D 1010 LNA',
    motorColor: 'Dull Blue Metallic',
    motorMods: 'Top Box Givi B32, Handguard Accossato',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    joinedDate: '05 Maret 2024',
  },
  {
    id: 'mem-2e',
    fullName: 'Kang Agum Ginanjar',
    nra: 'NTCI-BDG-012',
    email: 'agum.bdg@ntci.or.id',
    phone: '+62 813-7777-8888',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bandung Juara',
    chapterSlug: 'bandung-juara',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'D 1212 AGM',
    motorColor: 'Magma Black',
    motorMods: 'Akrapovic Exhaust, remap Y-CVT Sport',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    joinedDate: '10 Maret 2024',
  },
  {
    id: 'mem-2f',
    fullName: 'Kang Farhan Permana',
    nra: 'NTCI-BDG-015',
    email: 'farhan.bdg@ntci.or.id',
    phone: '+62 813-9999-0000',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bandung Juara',
    chapterSlug: 'bandung-juara',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'D 1515 FRH',
    motorColor: 'Elixir Dark Red',
    motorMods: 'Ohlins Rear Suspension',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    joinedDate: '15 Maret 2024',
  },
  {
    id: 'mem-2g',
    fullName: 'Bro Cecep Kurnia',
    nra: 'NTCI-BDG-022',
    email: 'cecep.bdg@ntci.or.id',
    phone: '+62 813-2222-9999',
    role: 'MEMBER',
    isVerified: true,
    chapterName: 'NTCI Chapter Bandung Juara',
    chapterSlug: 'bandung-juara',
    motorModel: 'Nmax Turbo Standard',
    motorYear: '2024',
    motorPlate: 'D 2222 CCP',
    motorColor: 'Ceramic Grey',
    motorMods: 'Windshield Touring Mid',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    joinedDate: '20 April 2024',
  },

  // Chapter Surabaya Coastal Members
  {
    id: 'mem-3',
    fullName: 'Rendy Pratama',
    nra: 'NTCI-SUB-003',
    email: 'rendy@ntci.or.id',
    phone: '+62 856-7891-2345',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Surabaya Coastal',
    chapterSlug: 'surabaya-coastal',
    motorModel: 'Nmax Turbo Standard',
    motorYear: '2024',
    motorPlate: 'L 5555 TC',
    motorColor: 'Ceramic Grey',
    motorMods: 'Windshield Tall Touring, Crashbar Custom',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '01 Maret 2024',
  },
  {
    id: 'mem-3b',
    fullName: 'Cak Sugeng Raharjo',
    nra: 'NTCI-SUB-005',
    email: 'sugeng.sub@ntci.or.id',
    phone: '+62 856-1111-2222',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Surabaya Coastal',
    chapterSlug: 'surabaya-coastal',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'L 5050 SGG',
    motorColor: 'Magma Black',
    motorMods: 'Dual Disc Brake, Shock YSS G-Sport',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    joinedDate: '05 Maret 2024',
  },
  {
    id: 'mem-3c',
    fullName: 'Cak Bayu Setiawan',
    nra: 'NTCI-SUB-009',
    email: 'bayu.sub@ntci.or.id',
    phone: '+62 856-3333-4444',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Surabaya Coastal',
    chapterSlug: 'surabaya-coastal',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'L 9090 BYU',
    motorColor: 'Elixir Dark Red',
    motorMods: 'Topbox Shad SH48, Touring Lights',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '12 Maret 2024',
  },
  {
    id: 'mem-3d',
    fullName: 'Ning Anita Wati',
    nra: 'NTCI-SUB-011',
    email: 'anita.sub@ntci.or.id',
    phone: '+62 856-5555-6666',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Surabaya Coastal',
    chapterSlug: 'surabaya-coastal',
    motorModel: 'Nmax Turbo Neo Version',
    motorYear: '2024',
    motorPlate: 'L 1111 ANT',
    motorColor: 'Dull Blue Metallic',
    motorMods: 'Crashbar Side Guard, Softseat Custom',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    joinedDate: '18 Maret 2024',
  },
  {
    id: 'mem-3e',
    fullName: 'Cak Doni Kurniawan',
    nra: 'NTCI-SUB-014',
    email: 'doni.sub@ntci.or.id',
    phone: '+62 856-7777-8888',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Surabaya Coastal',
    chapterSlug: 'surabaya-coastal',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'L 1414 DNI',
    motorColor: 'Magma Black',
    motorMods: 'Remap Y-CVT Sport, Knalpot Proliner',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '25 Maret 2024',
  },
  {
    id: 'mem-3f',
    fullName: 'Cak Eko Prasetyo',
    nra: 'NTCI-SUB-018',
    email: 'eko.sub@ntci.or.id',
    phone: '+62 856-9999-0000',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Surabaya Coastal',
    chapterSlug: 'surabaya-coastal',
    motorModel: 'Nmax Turbo Standard',
    motorYear: '2024',
    motorPlate: 'L 1818 EKO',
    motorColor: 'Ceramic Grey',
    motorMods: 'Intercom Bluetooth Sena 50S',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    joinedDate: '02 April 2024',
  },

  // Chapter Yogyakarta Mataram Members
  {
    id: 'mem-5',
    fullName: 'Agus Setiawan',
    nra: 'NTCI-JOG-005',
    email: 'agus.jogja@ntci.or.id',
    phone: '+62 818-0123-4567',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Yogyakarta Mataram',
    chapterSlug: 'yogyakarta-mataram',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'AB 8888 TURBO',
    motorColor: 'Magma Black',
    motorMods: 'Side Panniers Givi, GPS Navigation Holder',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '20 Mei 2024',
  },
  {
    id: 'mem-5b',
    fullName: 'Mas Bambang Sutrisno',
    nra: 'NTCI-JOG-007',
    email: 'bambang.jog@ntci.or.id',
    phone: '+62 818-1111-2222',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Yogyakarta Mataram',
    chapterSlug: 'yogyakarta-mataram',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'AB 7777 BBG',
    motorColor: 'Elixir Dark Red',
    motorMods: 'Windshield Touring High, Shock RCB',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    joinedDate: '25 Mei 2024',
  },
  {
    id: 'mem-5c',
    fullName: 'Mas Danang Wijaya',
    nra: 'NTCI-JOG-010',
    email: 'danang.jog@ntci.or.id',
    phone: '+62 818-3333-4444',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Yogyakarta Mataram',
    chapterSlug: 'yogyakarta-mataram',
    motorModel: 'Nmax Turbo Standard',
    motorYear: '2024',
    motorPlate: 'AB 1010 DNG',
    motorColor: 'Ceramic Grey',
    motorMods: 'Crashbar Black Powdercoating',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '01 Juni 2024',
  },
  {
    id: 'mem-5d',
    fullName: 'Mbak Dewi Lestari',
    nra: 'NTCI-JOG-012',
    email: 'dewi.jog@ntci.or.id',
    phone: '+62 818-5555-6666',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Yogyakarta Mataram',
    chapterSlug: 'yogyakarta-mataram',
    motorModel: 'Nmax Turbo Neo Version',
    motorYear: '2024',
    motorPlate: 'AB 1212 DWI',
    motorColor: 'Dull Blue Metallic',
    motorMods: 'Softseat Comfort, Top Box Shad',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    joinedDate: '10 Juni 2024',
  },
  {
    id: 'mem-5e',
    fullName: 'Mas Gito Raharjo',
    nra: 'NTCI-JOG-015',
    email: 'gito.jog@ntci.or.id',
    phone: '+62 818-7777-8888',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Yogyakarta Mataram',
    chapterSlug: 'yogyakarta-mataram',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'AB 1515 GTO',
    motorColor: 'Magma Black',
    motorMods: 'Remap Y-CVT, Lampu Tembak Gold',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    joinedDate: '15 Juni 2024',
  },
  {
    id: 'mem-5f',
    fullName: 'Mas Dimas Anggoro',
    nra: 'NTCI-JOG-018',
    email: 'dimas.jog@ntci.or.id',
    phone: '+62 818-9999-0000',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Yogyakarta Mataram',
    chapterSlug: 'yogyakarta-mataram',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'AB 1818 DMS',
    motorColor: 'Magma Black',
    motorMods: 'Intercom FreedConn T-Max',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    joinedDate: '20 Juni 2024',
  },

  // Chapter Bali Paradise Members
  {
    id: 'mem-6',
    fullName: 'I Made Suardana',
    nra: 'NTCI-BAL-006',
    email: 'suardana.bali@ntci.or.id',
    phone: '+62 878-6543-2109',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bali Paradise',
    chapterSlug: 'bali-paradise',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'DK 6666 MDE',
    motorColor: 'Magma Black',
    motorMods: 'Custom Carbon Trim, Exhaust Akrapovic',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '01 Juli 2024',
  },
  {
    id: 'mem-6b',
    fullName: 'I Wayan Gede',
    nra: 'NTCI-BAL-008',
    email: 'wayan.bali@ntci.or.id',
    phone: '+62 878-1111-2222',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bali Paradise',
    chapterSlug: 'bali-paradise',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'DK 8888 WYN',
    motorColor: 'Elixir Dark Red',
    motorMods: 'Shock Ohlins, Master Cylinder Brembo',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    joinedDate: '05 Juli 2024',
  },
  {
    id: 'mem-6c',
    fullName: 'Ni Putu Ayu',
    nra: 'NTCI-BAL-011',
    email: 'ayu.bali@ntci.or.id',
    phone: '+62 878-3333-4444',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bali Paradise',
    chapterSlug: 'bali-paradise',
    motorModel: 'Nmax Turbo Neo Version',
    motorYear: '2024',
    motorPlate: 'DK 1111 AYU',
    motorColor: 'Dull Blue Metallic',
    motorMods: 'Side Box Shad, LED Foglights',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    joinedDate: '10 Juli 2024',
  },
  {
    id: 'mem-6d',
    fullName: 'I Nyoman Kadek',
    nra: 'NTCI-BAL-014',
    email: 'kadek.bali@ntci.or.id',
    phone: '+62 878-5555-6666',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bali Paradise',
    chapterSlug: 'bali-paradise',
    motorModel: 'Nmax Turbo Standard',
    motorYear: '2024',
    motorPlate: 'DK 1414 KDK',
    motorColor: 'Ceramic Grey',
    motorMods: 'Windshield Touring Tall',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '15 Juli 2024',
  },
  {
    id: 'mem-6e',
    fullName: 'I Ketut Rai',
    nra: 'NTCI-BAL-017',
    email: 'rai.bali@ntci.or.id',
    phone: '+62 878-7777-8888',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bali Paradise',
    chapterSlug: 'bali-paradise',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'DK 1717 RAI',
    motorColor: 'Magma Black',
    motorMods: 'Remap Y-CVT, Velg Repaint Gold',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    joinedDate: '20 Juli 2024',
  },
  {
    id: 'mem-6f',
    fullName: 'I Made Agus',
    nra: 'NTCI-BAL-020',
    email: 'agus.bali@ntci.or.id',
    phone: '+62 878-9999-0000',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Bali Paradise',
    chapterSlug: 'bali-paradise',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'DK 2020 AGS',
    motorColor: 'Magma Black',
    motorMods: 'Intercom Cardo Packtalk',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    joinedDate: '25 Juli 2024',
  },

  // Chapter Medan Sumatra Members
  {
    id: 'mem-7',
    fullName: 'Fahmi Siregar',
    nra: 'NTCI-MED-007',
    email: 'fahmi.medan@ntci.or.id',
    phone: '+62 821-4321-8765',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Medan Sumatra',
    chapterSlug: 'medan-sumatra',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'BK 7777 FHM',
    motorColor: 'Magma Black',
    motorMods: 'Crashbar Heavy Duty, Side Panniers Givi 36L',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    joinedDate: '01 Agustus 2024',
  },
  {
    id: 'mem-7b',
    fullName: 'Bang Ucok Harahap',
    nra: 'NTCI-MED-009',
    email: 'ucok.medan@ntci.or.id',
    phone: '+62 821-1111-2222',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Medan Sumatra',
    chapterSlug: 'medan-sumatra',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'BK 9999 UCK',
    motorColor: 'Elixir Dark Red',
    motorMods: 'Shock YSS G-Top, Foglights Dual Color',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    joinedDate: '05 Agustus 2024',
  },
  {
    id: 'mem-7c',
    fullName: 'Bang Budi Nasution',
    nra: 'NTCI-MED-012',
    email: 'budi.medan@ntci.or.id',
    phone: '+62 821-3333-4444',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Medan Sumatra',
    chapterSlug: 'medan-sumatra',
    motorModel: 'Nmax Turbo Standard',
    motorYear: '2024',
    motorPlate: 'BK 1212 BUD',
    motorColor: 'Ceramic Grey',
    motorMods: 'Windshield Touring Tall',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '10 Agustus 2024',
  },
  {
    id: 'mem-7d',
    fullName: 'Kak Sarah Hasibuan',
    nra: 'NTCI-MED-015',
    email: 'sarah.medan@ntci.or.id',
    phone: '+62 821-5555-6666',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Medan Sumatra',
    chapterSlug: 'medan-sumatra',
    motorModel: 'Nmax Turbo Neo Version',
    motorYear: '2024',
    motorPlate: 'BK 1515 SRH',
    motorColor: 'Dull Blue Metallic',
    motorMods: 'Top Box Shad SH45',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    joinedDate: '15 Agustus 2024',
  },
  {
    id: 'mem-7e',
    fullName: 'Bang Taufik Hidayat',
    nra: 'NTCI-MED-018',
    email: 'taufik.medan@ntci.or.id',
    phone: '+62 821-7777-8888',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Medan Sumatra',
    chapterSlug: 'medan-sumatra',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'BK 1818 TFK',
    motorColor: 'Magma Black',
    motorMods: 'Remap Y-CVT, Knalpot Racing',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '20 Agustus 2024',
  },
  {
    id: 'mem-7f',
    fullName: 'Bang Reza Pahlevi',
    nra: 'NTCI-MED-022',
    email: 'reza.medan@ntci.or.id',
    phone: '+62 821-9999-0000',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Medan Sumatra',
    chapterSlug: 'medan-sumatra',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'BK 2222 RZA',
    motorColor: 'Magma Black',
    motorMods: 'Intercom Cardo Packtalk Bold',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    joinedDate: '25 Agustus 2024',
  },

  // Chapter Semarang Central (Embrio)
  {
    id: 'mem-8',
    fullName: 'Bro Hendra "Turbo" Gunawan',
    nra: 'NTCI-SMG-001',
    email: 'hendra.smg@ntci.or.id',
    phone: '+62 813-2222-3333',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Semarang Central (Prospek)',
    chapterSlug: 'semarang-central',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'H 1111 HND',
    motorColor: 'Magma Black',
    motorMods: 'Carbon Parts, Akrapovic Exhaust',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    joinedDate: '01 September 2024',
  },
  {
    id: 'mem-8b',
    fullName: 'Bro Arif Hidayat',
    nra: 'NTCI-SMG-003',
    email: 'arif.smg@ntci.or.id',
    phone: '+62 813-4444-5555',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Semarang Central (Prospek)',
    chapterSlug: 'semarang-central',
    motorModel: 'Nmax Turbo Tech MAX',
    motorYear: '2024',
    motorPlate: 'H 3333 ARF',
    motorColor: 'Elixir Dark Red',
    motorMods: 'Shock YSS, Windshield Mid',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '05 September 2024',
  },

  // Chapter Makassar Celebes (Embrio)
  {
    id: 'mem-9',
    fullName: 'Daeng Rahmat',
    nra: 'NTCI-MKS-001',
    email: 'rahmat.mks@ntci.or.id',
    phone: '+62 852-9988-7766',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Makassar Celebes (Prospek)',
    chapterSlug: 'makassar-celebes',
    motorModel: 'Nmax Turbo Tech MAX Ultimate',
    motorYear: '2024',
    motorPlate: 'DD 1111 RHM',
    motorColor: 'Magma Black',
    motorMods: 'Full Crashbar, Foglights 60W',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    joinedDate: '10 September 2024',
  },
  {
    id: 'mem-9b',
    fullName: 'Daeng Syamsul',
    nra: 'NTCI-MKS-002',
    email: 'syamsul.mks@ntci.or.id',
    phone: '+62 852-1111-3333',
    role: 'CHAPTER_ADMIN',
    isVerified: true,
    chapterName: 'NTCI Chapter Makassar Celebes (Prospek)',
    chapterSlug: 'makassar-celebes',
    motorModel: 'Nmax Turbo Neo Version',
    motorYear: '2024',
    motorPlate: 'DD 2222 SYM',
    motorColor: 'Dull Blue Metallic',
    motorMods: 'Top Box Givi',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    joinedDate: '15 September 2024',
  },
];

export const INITIAL_EVENTS: EventData[] = [
  {
    id: 'ev-1',
    title: 'Kopdar Wajib & Bedah Fitur Y-CVT Nmax Turbo',
    slug: 'kopdar-wajib-bedah-fitur-y-cvt',
    category: 'WORKSHOP',
    description: 'Kopdar rutin sekaligus sesi edukasi teknis bersama mekanik tersertifikasi Yamaha mengenai optimalisasi fitur Y-Shift dan Turbo Riding Mode pada Nmax Turbo.',
    location: 'Plaza Senayan Pintu 1 & Resto Bikers Corner',
    meetingPoint: 'Parkiran Timur Senayan Jam 19:30 WIB',
    startDate: '2026-08-15T20:00:00Z',
    chapterName: 'NTCI Chapter Jakarta Raya',
    chapterSlug: 'jakarta-raya',
    bannerUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80',
    attendingCount: 68,
  },
  {
    id: 'ev-2',
    title: 'National Grand Touring: Jelajah Lintas Jalur Selatan Java 2026',
    slug: 'national-grand-touring-lintas-selatan-2026',
    category: 'TOURING',
    description: 'Touring akbar nasional lintas provinsi dari Bandung menuju Yogyakarta via Jalur Pantai Selatan (Pansela). Terbuka untuk seluruh anggota NTCI se-Indonesia.',
    location: 'Bandung - Pangandaran - Kebumen - Yogyakarta',
    meetingPoint: 'Gedung Sate Bandung, Sabtu Jam 05:00 WIB',
    startDate: '2026-09-10T05:00:00Z',
    endDate: '2026-09-13T18:00:00Z',
    chapterName: 'NTCI Chapter Bandung Juara',
    chapterSlug: 'bandung-juara',
    bannerUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80',
    attendingCount: 154,
  },
  {
    id: 'ev-3',
    title: 'NTCI Social Action: Santunan & Bakti Sosial Pesisir Pantai Sanur',
    slug: 'social-action-pantai-sanur-bali',
    category: 'SOCIAL_CSR',
    description: 'Kegiatan kepedulian sosial berupa pembersihan area pantai serta penyerahan bantuan alat tangkap nelayan & beasiswa anak pesisir.',
    location: 'Pantai Matahari Terbit, Sanur, Bali',
    meetingPoint: 'Basecamp NTCI Bali Jam 07:00 WITA',
    startDate: '2026-08-23T08:00:00Z',
    chapterName: 'NTCI Chapter Bali Paradise',
    chapterSlug: 'bali-paradise',
    bannerUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    attendingCount: 42,
  },
  {
    id: 'ev-4',
    title: 'Celebration: 2nd Anniversary NTCI & Jambore Nasional 2026',
    slug: '2nd-anniversary-ntci-jamnas-2026',
    category: 'ANNIVERSARY',
    description: 'Puncak perayaan ulang tahun NTCI ke-2. Menampilkan kontes modifikasi Nmax Turbo, pentas musik, bazaar UMKM otomotif, dan safety riding exhibition.',
    location: 'Candi Prambanan Open Field, Yogyakarta',
    meetingPoint: 'Lapangan Utama Prambanan',
    startDate: '2026-11-21T09:00:00Z',
    endDate: '2026-11-22T23:00:00Z',
    chapterName: 'NTCI Chapter Yogyakarta Mataram',
    chapterSlug: 'yogyakarta-mataram',
    bannerUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    attendingCount: 310,
  },
  {
    id: 'ev-5',
    title: 'Coastal Night Ride & Kopdar Gabungan Suramadu',
    slug: 'coastal-night-ride-suramadu',
    category: 'KOPDAR',
    description: 'Night riding melintasi Jembatan Suramadu dilanjutkan santap malam bersama seluruh rider Nmax Turbo area Jatim.',
    location: 'Jembatan Suramadu & Resto Pesisir Bangkalan',
    meetingPoint: 'Taman Bungkul Surabaya Jam 20:00 WIB',
    startDate: '2026-09-05T20:00:00Z',
    chapterName: 'NTCI Chapter Surabaya Coastal',
    chapterSlug: 'surabaya-coastal',
    bannerUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80',
    attendingCount: 75,
  },
  {
    id: 'ev-6',
    title: 'Sumatra Challenge: Touring Trans-Sumatera Chapter Medan',
    slug: 'sumatra-challenge-touring-trans-sumatera',
    category: 'TOURING',
    description: 'Touring tantangan rute Medan - Parapat Danau Toba - Berastagi menguji ketangguhan fitur Turbo Riding Mode.',
    location: 'Medan - Danau Toba - Berastagi',
    meetingPoint: 'Lapangan Merdeka Medan Jam 06:00 WIB',
    startDate: '2026-10-15T06:00:00Z',
    chapterName: 'NTCI Chapter Medan Sumatra',
    chapterSlug: 'medan-sumatra',
    bannerUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80',
    attendingCount: 50,
  },
];

export const INITIAL_ARTICLES: ArticleData[] = [
  {
    id: 'art-1',
    title: 'Panduan Perawatan Sistem Y-CVT Yamaha Nmax Turbo Agar Tetap Responsif',
    slug: 'panduan-perawatan-y-cvt-nmax-turbo',
    category: 'TECH_TIPS',
    excerpt: 'Sistem transmisi elektronik Y-CVT pada Nmax Turbo membutuhkan perhatian khusus saat perawatan berkala. Simak 5 langkah mudah menjaga keawetannya.',
    content: `Yamaha Nmax Turbo menghadirkan teknologi revolusioner **Y-CVT (Yamaha Electric Continuously Variable Transmission)** yang menggantikan roller konvensional dengan motor penggerak elektronik.

### 1. Servis Berkala Elektrikal Y-CVT
Pastikan konektor sensor dan motor Y-CVT selalu bersih dari debu dan kelembapan ekstrim. Lakukan scan diagnostic di bengkel resmi Yamaha setiap 4.000 KM.

### 2. Gunakan Oli Transmisi & Mesin Berkualitas
Suhu mesin yang terjaga sangat berpengaruh pada performa kontrol elektronik Y-CVT. Gunakan oli berstandar sintetis penuh dengan viskositas yang direkomendasikan pabrikan.

### 3. Hindari Memaksa Y-Shift di Kecepatan Terlalu Rendah
Penggunaan tombol Y-Shift (Low, Medium, High) paling efektif digunakan saat berakselerasi menyalip atau membutuhkan engine brake saat turunan curam.`,
    authorName: 'Divisi Teknik & Modifikasi NTCI',
    authorRole: 'Pengurus Pusat',
    coverImage: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80',
    createdAt: '28 Juli 2026',
    readTime: '4 Menit Baca',
  },
  {
    id: 'art-2',
    title: 'Laporan Touring: Jelajah KM 0 Sabang Oleh NTCI Chapter Medan',
    slug: 'laporan-touring-sabang-km-0-medan',
    category: 'TOURING_REPORT',
    excerpt: 'Perjalanan penuh tantangan melintasi 1.200 KM jalur Trans-Sumatera dan menyeberang ke Pulau Weh Sabang successfully ditaklukkan rombongan NTCI.',
    content: `Sebanyak 18 unit Nmax Turbo dari NTCI Chapter Medan menyelesaikan ekspedisi **Jelajah Titik Nol KM Sabang**.

Selama 5 hari perjalanan, rombongan melintasi keindahan alam Banda Aceh, perbukitan Seulawah, hingga keindahan Pantai Iboih Sabang. Ketangguhan Nmax Turbo teruji sempurna di tanjakan terjal dengan mode *T-Mode & Y-Shift Turbo*.`,
    authorName: 'Fahmi Siregar',
    authorRole: 'Ketua Chapter Medan',
    coverImage: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80',
    createdAt: '15 Juli 2026',
    readTime: '6 Menit Baca',
  },
  {
    id: 'art-3',
    title: 'Etika Group Riding & Kode Isyarat Tangan (Hand Signals) Saat Touring',
    slug: 'etika-group-riding-dan-hand-signals',
    category: 'SAFETY_RIDING',
    excerpt: 'Keselamatan saat touring kelompok ditentukan oleh komunikasi antar biker. Pelajari kode isyarat tangan standar NTCI.',
    content: `Dalam setiap kegiatan touring resmi NTCI, keselamatan anggota adalah prioritas nomor satu. 

### Susunan Rombongan
- **Road Captain (RC)**: Berada paling depan memimpin rute.
- **Sweeper**: Berada di posisi tengah & paling belakang memastikan tidak ada rombongan yang tertinggal.

### Isyarat Tangan Penting
1. **Satu Jari Ke Atas**: Membentuk formasi 1 baris.
2. **Kaki Kiri / Kanan Turun**: Peringatan ada lubang/rintangan di jalan sebelah kiri/kanan.
3. **Kepalan Tangan Diatas**: Tanda rombongan harus berhenti (Stop).`,
    authorName: 'Divisi Safety Riding NTCI',
    authorRole: 'Pengurus Pusat',
    coverImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80',
    createdAt: '02 Juni 2026',
    readTime: '5 Menit Baca',
  },
];

export const INITIAL_DOCUMENTS: DocumentData[] = [
  {
    id: 'doc-1',
    title: 'Anggaran Dasar & Anggaran Rumah Tangga (AD-ART) NTCI 2024-2029',
    category: 'AD_ART',
    description: 'Dokumen konstitusi resmi organisasi Nmax Turbo Club Indonesia yang disahkan dalam Musyawarah Nasional (MUNAS) I.',
    fileUrl: '/docs/AD-ART-NTCI-2024.pdf',
    fileSize: '2.4 MB',
    updatedAt: '12 Januari 2024',
  },
  {
    id: 'doc-2',
    title: 'Standard Operating Procedure (SOP) Touring & Konvoi Resmi',
    category: 'SOP',
    description: 'Panduan tata cara pelaksanaan touring resmi, persyaratan kelengkapan motor, dan prosedur administrasi perizinan.',
    fileUrl: '/docs/SOP-Touring-NTCI.pdf',
    fileSize: '1.1 MB',
    updatedAt: '05 Maret 2024',
  },
  {
    id: 'doc-3',
    title: 'Pedoman Pembentukan Chapter Baru & Syarat Pendirian',
    category: 'REGULATION',
    description: 'Petunjuk teknis bagi anggota daerah yang ingin mengajukan pembentukan Chapter NTCI resmi di kabupaten/kota.',
    fileUrl: '/docs/Pedoman-Chapter-NTCI.pdf',
    fileSize: '850 KB',
    updatedAt: '20 April 2024',
  },
];

export const INITIAL_MERCHANDISE: MerchandiseData[] = [
  {
    id: 'merch-1',
    name: 'NTCI Official Touring Jacket Waterproof',
    category: 'Apparel',
    price: 485000,
    description: 'Jaket riding cordura premium angin & hujan dengan protector siku, bahu, dan punggung. Dilengkapi logo bordir presisi NTCI.',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
    buyUrl: 'https://wa.me/6281234567890?text=Halo%20Admin%20NTCI,%20saya%20mau%20pesan%20Jaket%20Touring',
    isAvailable: true,
  },
  {
    id: 'merch-2',
    name: 'NTCI Official Polo Shirt Premium Cotton',
    category: 'Apparel',
    price: 175000,
    description: 'Polo shirt elegan bahan lacoste cotton CVC 30s dengan kerah kokoh dan bordir komputer logo NTCI & Bendera Merah Putih.',
    imageUrl: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=600&q=80',
    buyUrl: 'https://wa.me/6281234567890?text=Halo%20Admin%20NTCI,%20saya%20mau%20pesan%20Polo%20Shirt',
    isAvailable: true,
  },
  {
    id: 'merch-3',
    name: 'Official Patch Bordir & Sticker Pack Reflective 3M',
    category: 'Accessories',
    price: 65000,
    description: 'Set stiker fosfor menyala saat tersorot lampu malam (3M material) + Emblem patch velcro untuk rompi/jaket.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    buyUrl: 'https://wa.me/6281234567890?text=Halo%20Admin%20NTCI,%20saya%20mau%20pesan%20Sticker%20Pack',
    isAvailable: true,
  },
];

export const INITIAL_SPONSORS: SponsorData[] = [
  {
    id: 'sp-1',
    name: 'Yamaha Official Dealer Network',
    category: 'Main Sponsor / Partner',
    discountDetail: 'Diskon 10% Jasa Servis & Sparepart Asli di Dealer Tertentu dengan E-KTA NTCI',
    logoUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://yamaha-motor.co.id',
  },
  {
    id: 'sp-2',
    name: 'Shell Lubricants Indonesia',
    category: 'Oli & Fluid',
    discountDetail: 'Free Ganti Oli & Cashback 15% Setiap Pembelian Shell Advance Ultra Synthetic',
    logoUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://shell.co.id',
  },
  {
    id: 'sp-3',
    name: 'Planet Ban Authorized Outlet',
    category: 'Ban & Velg',
    discountDetail: 'Potongan Harga Rp 25.000 per Ban Soft Compound / Touring + Free Nitrogen Seumur Hidup',
    logoUrl: 'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://planetban.com',
  },
];

export const INITIAL_EMERGENCY: EmergencyContactData[] = [
  {
    id: 'em-1',
    chapterName: 'NTCI Chapter Jakarta Raya',
    contactPerson: 'Bambang / Bro Storing JKT',
    roleOrLocation: 'Towing & Mobil Storing Darurat Jabodetabek',
    phone: '+62 812-3456-7890',
  },
  {
    id: 'em-2',
    chapterName: 'NTCI Chapter Bandung Juara',
    contactPerson: 'Dicky / Kang Mekanik BDG',
    roleOrLocation: 'Mekanik Panggilan Area Nagreg - Puncak - Bandung',
    phone: '+62 813-9876-5432',
  },
  {
    id: 'em-3',
    chapterName: 'NTCI Chapter Yogyakarta Mataram',
    contactPerson: 'Bro Agus Jogja',
    roleOrLocation: 'Posko Rest Area & Towing Jalur Pansela Jogja',
    phone: '+62 818-0123-4567',
  },
  {
    id: 'em-4',
    chapterName: 'NTCI Chapter Surabaya Coastal',
    contactPerson: 'Bro Rendy Suramadu',
    roleOrLocation: 'Bantuan Emergency Storing Area Jalur Pantura Jatim',
    phone: '+62 856-7891-2345',
  },
];
